language: ruby
script: bundle exec rake spec 
rvm:
#  - ruby-head
  - 2.2.0
  - 2.1.5
  - 2.1.4
  - 2.1.3
  - 2.1.1
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
notifications:
  email:
    - ndushay@stanford.edu
    - cabeer@stanford.edu
    - wmene@stanford.edu
